version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/drawing-duo_backend_dist
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/execute.sh
      timeout: 600
      runas: ubuntu
